# This is a basic workflow to help you get started with Actions

name: Moon Curl Action

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  moon-curl:
    runs-on: ubuntu-latest

    steps: 
    - name: Executer la commande curl vers wttr.in/Moon
      run: curl wttr.in/Moon
    
   
